# -*- coding: utf-8 -*-
"""CECS456.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2r563CrKC3gXggi47uH5_SlxIukmZO8

Importing Kaggle Dataset
"""

!pip install -q torch torchvision scikit-learn kaggle

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d prasunroy/natural-images
!mkdir -p data
!unzip -q natural-images.zip -d data/natural_images

!mv data/natural_images/natural_images/* data/natural_images/
!rmdir data/natural_images/natural_images


!ls data/natural_images
!rm -rf data/natural_images/data

!ls -la data/natural_images

!find data/natural_images -maxdepth 1 -type d -print

"""Setup"""

import tensorflow as tf
from tensorflow import keras
import sklearn
import numpy as np
np.random.seed(42)
import matplotlib as mpl
import matplotlib.pyplot as plt

"""Load Dataset"""

DATA_DIR = "data/natural_images"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.15,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.15,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(class_names)

from tensorflow.keras import layers, models
cnn = models.Sequential([
    layers.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),
    layers.Rescaling(1./255),

    layers.Conv2D(64, 7, padding="same", activation="relu"),
    layers.MaxPool2D(),

    layers.Conv2D(128, 3, padding="same", activation="relu"),
    layers.Conv2D(128, 3, padding="same", activation="relu"),
    layers.MaxPool2D(),

    layers.Conv2D(256, 3, padding="same", activation="relu"),
    layers.Conv2D(256, 3, padding="same", activation="relu"),
    layers.MaxPool2D(),

    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation="softmax"),
])

cnn.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
history = cnn.fit(train_ds, validation_data=val_ds, epochs=15)

val_loss, val_acc = cnn.evaluate(val_ds, verbose=1)
print(f"Validation loss: {val_loss:.4f}")
print(f"Validation accuracy: {val_acc:.4f}")

import numpy as np
import matplotlib.pyplot as plt

images, labels = next(iter(val_ds))
probs = cnn.predict(images, verbose=0)
preds = np.argmax(probs, axis=1)

plt.figure(figsize=(12, 6))
for i in range(6):
    plt.subplot(2, 3, i+1)
    plt.imshow(images[i].numpy().astype("uint8"))
    true_name = class_names[int(labels[i])]
    pred_name = class_names[int(preds[i])]
    conf = np.max(probs[i])
    plt.title(f"True: {true_name}\nPred: {pred_name} ({conf:.2f})")
    plt.axis("off")
plt.tight_layout()
plt.show()